export const DEFAULT_POSITIVE_TERMS = [
  ["AI Agent", 18],
  ["Agent", 8],
  ["LLM", 12],
  ["RAG", 12],
  ["MCP", 12],
  ["AIGC", 8],
  ["OpenAI", 10],
  ["Codex", 10],
  ["Cursor", 8],
  ["Claude", 8],
  ["大模型", 12],
  ["智能体", 14],
  ["模型部署", 12],
  ["提示词", 6],
  ["工程化", 8],
  ["嵌入式", 14],
  ["Linux", 12],
  ["Android", 10],
  ["驱动", 14],
  ["内核", 10],
  ["MTK", 12],
  ["高通", 10],
  ["Qualcomm", 10],
  ["Hypervisor", 14],
  ["virtio", 14],
  ["vsock", 14],
  ["AUTOSAR", 10],
  ["C++", 8],
  ["Python", 8],
  ["DevOps", 12],
  ["SRE", 10],
  ["K8s", 12],
  ["Kubernetes", 12],
  ["Docker", 8],
  ["Jenkins", 8],
  ["Argo", 8],
  ["Helm", 8],
  ["Terraform", 8],
  ["Prometheus", 8],
  ["Grafana", 8],
  ["云原生", 10],
  ["运维开发", 12],
  ["平台工程", 10],
  ["自动化", 8],
  ["系统运维", 8],
  ["测试开发", 12],
  ["自动化测试", 10],
  ["车载测试", 10],
  ["HIL", 10],
  ["座舱", 8],
  ["智驾", 8],
];

export const DEFAULT_NEGATIVE_TERMS = [
  ["销售", -30],
  ["客服", -30],
  ["人事", -25],
  ["HR", -22],
  ["招聘", -22],
  ["行政", -25],
  ["财务", -25],
  ["会计", -25],
  ["审计", -25],
  ["市场", -18],
  ["营销", -18],
  ["电商运营", -22],
  ["运营专员", -22],
  ["产品经理", -12],
  ["讲师", -20],
  ["教师", -20],
  ["培训", -18],
  ["实习", -20],
  ["兼职", -25],
];

export const DEFAULT_BATCH_POLICY = {
  max_per_batch: 15,
  batch_cooldown_ms: 45000,
  jitter_ms: 10000,
  stop_on_access_limited: true,
};
